<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
    <ProjectReference Include="..\Messaging.Services\Messaging.Services.csproj" />
    <ProjectReference Include="..\Messaging.Storage\Messaging.Storage.csproj" />
  </ItemGroup>

</Project>
